name = "serverless-docs-stack"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
PUBLIC_BASE_URL = "https://public-url-from-cf.pages.dev"          # Set to your public URL once you have one
PUBLIC_GOOGLE_OAUTH_REDIRECT_PATH = "/auth/oauth/google/callback"

[[d1_databases]]
binding = "DB"
database_name = "serverless-docs-db"
database_id = ""
